Feat/list cameras for sensor
astrobin/astrobin-ng pull request #1472
Opened 2023-05-26 16:04 UTC by sastels

2023-05-26 16:32 UTC, sastels commented on src/app/shared/components/equipment/summaries/item-summary/item-summary.component.ts
> +        )
This is where the non-subitem version is displayed, probably don't want this.

2023-05-27 01:04 UTC, sastels commented
Probably should add a test somewhere that the correct cameras show up?

2023-05-27 06:57 UTC, siovene commented on src/app/shared/components/equipment/summaries/item-summary/item-summary.component.ts
> +        )
> Probably should add a test somewhere that the correct cameras show up?

You can do this both in terms of unit tests (see `sensor.service.spec.ts`) or as e2e test with Cypress (see various `create-camera-*.js` in `/cypress/integration/equipment/explorer`.

2023-05-30 08:45 UTC, siovene requested changes

2023-05-30 08:45 UTC, siovene commented on src/app/features/equipment/services/sensor.service.ts
> +            ),
You don't need the `switchMap` to select the brands and then  map to `(camera, brand)` (I know it's used in other places, and I guess you took inspiration from CameraServices), but the API serializers adds a `brandName` property, so you can just use that.

2023-05-30 08:45 UTC, siovene commented on src/app/features/equipment/services/sensor.service.ts
> +            )
Because of the comment above, this would just use `camera.brandName`.

2023-05-30 08:45 UTC, siovene commented on src/app/features/equipment/services/sensor.service.ts
> +        return merge(...cameraProperties).pipe(reduce((a, b) => a + " &middot; " + b, ""));
This is much simpler if written as:

```
 return combineLatest(cameraProperties).pipe(
    map(cameras => cameras.join("&middot;"))
 );
```

2023-05-30 08:45 UTC, siovene commented on src/app/features/equipment/services/sensor.service.ts
> +        let cameraProperties = [];
This is better naemd `cameras$`.

- It's not properties, it's actual cameras
- The `$` suffix is a naming convention that indicates observables.

2023-06-03 00:19 UTC, sastels commented on src/app/features/equipment/services/sensor.service.ts
> +        return merge(...cameraProperties).pipe(reduce((a, b) => a + " &middot; " + b, ""));
oh nice! I saw the `combineLatest` function but didn't think it would work here (ie didn't know what it was doing 😅 )

2023-06-03 00:24 UTC, sastels commented on src/app/shared/components/equipment/summaries/item-summary/item-summary.component.ts
> +    }
yeah, this was "try to put it in as a subitem too to see if that makes sense"

2023-06-03 00:30 UTC, sastels commented on src/app/features/equipment/services/sensor.service.ts
> +        let cameraProperties = [];
I admit these dollar signs everywhere made me a bit nervous. But very useful to see the observables.

2023-06-03 00:59 UTC, sastels commented
Running with current master of astrobin shows n/a for cameras:

![image](https://github.com/astrobin/astrobin-ng/assets/8228248/3421a6d1-6da8-40ea-9183-19b542e3a8b8)

(Presumably this is ok since we'll merge in the astrobin changes before this PR)

2023-06-03 01:27 UTC, sastels commented
oh, good formatting on your tables! If there are too many cameras to fit in the line they start going down to the next line.

![image](https://github.com/astrobin/astrobin-ng/assets/8228248/0cdf3935-44e0-4a2b-9f5d-319d20164025)

2023-06-03 07:45 UTC, siovene commented
> oh, good formatting on your tables! If there are too many cameras to fit in the line they start going down to the next line.
> 
> ![image](https://user-images.githubusercontent.com/8228248/243027408-0cdf3935-44e0-4a2b-9f5d-319d20164025.png)

I'm thinking, and sorry about not mentioning this before, if we should only show a maximum number of cameras (say 3) and then ", and XX more".

I just checked the database, and the most popular sensor is featured in 30 cameras, so that list would be quote long.

So basically check if `cameras.length > 3` and you show a different template. To show the additional cameras, you can use the `InformationDialogComponent` modal (it's used in lots of places).

Let me know if you think it's a good idea!

2023-06-10 08:04 UTC, siovene commented on src/app/features/equipment/services/sensor.service.ts
> +              `<a href=/equipment/explorer/camera/${camera.id}> ${camera.brandName ? camera.brandName : this.translateService.instant("(DIY)")} ${camera.name}</a>`
Hmm the `href` should be a last resort, I think. When you do an `href` link like, the browser will literally reload the whole app. We want to use Angular's routing, with `[routerLink]` but I'm pretty sure it will not work if it's used with a literal string that way.

I think the clean way to do this would be to use a component we already have (`EquipmentItemDisplayNameComponent`) but again I don't know if it will work if added to the page this way.

Maybe try that and if it gets too complicated just leave the `href` solution for now :)

2023-06-22 16:52 UTC, sastels commented on src/app/features/equipment/services/sensor.service.ts
> +              `<a href=/equipment/explorer/camera/${camera.id}> ${camera.brandName ? camera.brandName : this.translateService.instant("(DIY)")} ${camera.name}</a>`
So I think that we want to send `item-summary.componant.html` a list of cameras or camera ids for the sensor (or the first 3 I suppose) and have the template loop over them and use something like
```
                  <astrobin-equipment-item-display-name
                    [itemId]="1"
                    [itemType]="CAMERA"
                    [enableNameLink]="true"
                  ></astrobin-equipment-item-display-name>
```
to show the cameras with a link. I put ☝️ in the template and instead of a link to the camera with id 1 I get moving periods and no link
![image](https://github.com/astrobin/astrobin-ng/assets/8228248/e34d7dfb-f375-42f2-85b4-6a588bae1df2)

Any thoughts?

2023-06-22 16:55 UTC, sastels commented
> 

That modal is cool but I'm having problems getting it to work 😞 Tried to add a link to the template with
```
                  <a  (click)="property.showExtraCameras()"> More Cameras Link 2</a> <!-- not a link ? -->
```
but I just get text and no link.

2023-06-23 16:37 UTC, siovene commented on src/app/features/equipment/services/sensor.service.ts
> +              `<a href=/equipment/explorer/camera/${camera.id}> ${camera.brandName ? camera.brandName : this.translateService.instant("(DIY)")} ${camera.name}</a>`
The moving dots come from the `TextLoadingIndicatorComponent` so it means that the `EquipmentItemDisplayNameComponent` is stuck in a loading state: `itemName` is not being set.

If you're passing that HTML as a literal from `SensorService.getPrintableProperty$`, I don't think that's going to work.

The cleanest way of doing it (for some definition of clean, I know 🤣) is to move some things up to the `ItemSummaryComponent`.

For instance, look at `function _variantOfProperty`, how it sets a link. In the HTML, then you have:

```HTML
            <td class="property-value">
              <ng-container *ngIf="!!property.link; else noLink">
                <a [routerLink]="property.link">
                  <ng-container *ngTemplateOutlet="propertyValueTemplate"></ng-container>
                </a>
              </ng-container>
```

So the `ItemSummaryComponent` is already built to deal with property values that have a link: you just need to leverage that.

2023-06-23 17:30 UTC, siovene reviewed
Something is causing `LoadBrands` to be dispatched in an infinite loop (you can see that the page becomes unresponsive, and if you install the Chrome extension "Redux" you can see what ngrx actions are happening! I'm gonna take over a little bit now so I can set you off on the right track! :)

2023-06-23 17:30 UTC, siovene commented on src/app/features/equipment/services/sensor.service.ts
> +          const suffix$ = of("and " + (cameras$.length - 3) + " more")
@sastels please note: this needs to be localized. As before, much better to let the `ItemSummaryComponent` deal with this decision about displaying only 3 with the rest in a modal.

2023-06-23 17:30 UTC, siovene commented on src/app/features/equipment/services/sensor.service.ts
> +  }
This is UI and belongs to a the `ItemSummaryComponent`, not to this service.

2023-06-23 17:30 UTC, siovene commented on src/app/shared/components/equipment/summaries/item-summary/item-summary.component.html
> +          SJA
Oopsie :)

2023-06-23 18:22 UTC, siovene commented
@sastels please see this:

https://github.com/astrobin/astrobin-ng/commit/853f658894d423e97e1732a17454c3dc87105082

I couldn't commit directly to your branch because you're on a fork, but I think you can cherry-pick it somehow (or worst case apply a patch).

As explained in the commit, we simply needed to give up the idea of doing this kind of logic in the sensor service, because it just had too much UI going on.

This way there's an unsightly `if (instanceOfSensor(this.item))` in `ItemSummaryComponent`, but it wouldn't be the first one. It's okay if that component has some knowledge of the equipment items.

I generalized it a little bit by using a `relatedItem` field, which is kinda like `subItem`.

Everything seems to work fine but I didn't run tests. Feel free to see if anything needs to be polished or tested, or let me know if you'd like me to finish things up!

Thanks!

2023-06-25 20:16 UTC, sastels commented
This is really cool - thanks!

I think I'm starting to understand how the typescript and html templates work together 😅 

Noticed a couple little things I think I can clean up!

2023-06-25 20:35 UTC, siovene commented
@sastels awesome! Sorry that I didn't suggest this strategy right off the bat... hindsight is 20/20 tho :)

2023-06-25 22:35 UTC, sastels commented
The middot isn't centered very well. It seems that an [anchor often gets a space at the end if there's a newline in the html after the anchor](https://stackoverflow.com/questions/6902237/css-unwanted-spacing-between-anchor-tag-elements) 😞 
![image](https://github.com/astrobin/astrobin-ng/assets/8228248/a8e9e550-e497-4aed-aa05-8ad97e3faa30)

We could do something hacky as is discussed in that post, but that's probably just making the code confusing and complicated. We could also:
- add 2 spaces after the middot 
![image](https://github.com/astrobin/astrobin-ng/assets/8228248/e6a79a34-84cd-401c-8820-183d195f5291)
- not use a middot (adding another space to add a bit more separation)
![image](https://github.com/astrobin/astrobin-ng/assets/8228248/b512f7be-8dc9-4cbe-8d8d-2a159fa548b8)
- something else?

I lean towards the middot with a couple spaces after it... kinda like the dot. What do you think?

2023-06-26 07:47 UTC, siovene commented
> @siovene The middot isn't centered very well. It seems that an [anchor often gets a space at the end if there's a newline in the html after the anchor](https://stackoverflow.com/questions/6902237/css-unwanted-spacing-between-anchor-tag-elements) 😞 ![image](https://user-images.githubusercontent.com/8228248/248590985-a8e9e550-e497-4aed-aa05-8ad97e3faa30.png)
> 
> We could do something hacky as is discussed in that post, but that's probably just making the code confusing and complicated. We could also:
> 
> * add 2 spaces after the middot
>   ![image](https://user-images.githubusercontent.com/8228248/248591392-e6a79a34-84cd-401c-8820-183d195f5291.png)
> * not use a middot (adding another space to add a bit more separation)
>   ![image](https://user-images.githubusercontent.com/8228248/248591914-b512f7be-8dc9-4cbe-8d8d-2a159fa548b8.png)
> * something else?
> 
> I lean towards the middot with a couple spaces after it... kinda like the dot. What do you think?

Hi @sastels,
I haven't run this locally to check, but it seems like this might be fixed more neatly by using some mark-up and CSS?

For instance, add a class `related-items` to the `tr`, then add a `<span class="separator">` around the `&middot;`, then use CSS to specify exactly how much margin/padding you want for `astrobin-equipment-item-display-name` and `.separator` inside `.related-items`.

Let me know if it works and thank you!

2023-07-01 21:12 UTC, sastels commented
Haven't played with css in a while! So I added a bit of padding to make things look better:
If there are 2 or less:
![image](https://github.com/astrobin/astrobin-ng/assets/8228248/acfde417-8618-4aeb-bde4-8cf634898ac5)
3 or more:
![image](https://github.com/astrobin/astrobin-ng/assets/8228248/45f53e4e-e157-4f31-b8c4-20c5d1dc8e1e)
with modal:
![image](https://github.com/astrobin/astrobin-ng/assets/8228248/a7a6a39e-2b77-410f-a077-a2e3fa486428)

2023-07-02 00:25 UTC, sastels commented on src/app/features/equipment/services/sensor.service.spec.ts
> +        expect(value).toEqual("10%"); // Can't both be true
this unit test passes which is not great 😬

2023-07-02 08:19 UTC, siovene commented on src/app/features/equipment/services/sensor.service.spec.ts
> +        expect(value).toEqual("10%"); // Can't both be true
@sastels LOL, my bad! Let me explain what's happening and how it can be fixed:

The test is succeeding because it's ending even before all those expects are checked. `getPrintableProperty$` is asynchronous so the observables never complete because the test fails.

How to fix:

 - Split up each check into a different `it` test
 - Add the `done`  function in to the arguments of the `it` function
 - Call `done()` after the expect

Example:

```
    it("should work for all properties'", (done) => {
      const sensor = SensorGenerator.sensor({
        quantumEfficiency: 10,
        pixelSize: 7.4,
        pixelWidth: 800,
        pixelHeight: 600,
        sensorWidth: 25,
        sensorHeight: 20,
        fullWellCapacity: 5,
        readNoise: 1000,
        frameRate: 24,
        adc: 12,
        colorOrMono: ColorOrMono.M
      });

      service.getPrintableProperty$(sensor, SensorDisplayProperty.QUANTUM_EFFICIENCY).subscribe(value => {
        expect(value).toEqual("999%"); // This test should fail
        expect(value).toEqual("10%"); // Can't both be true
        done();
      });
    });
```

2023-07-08 16:21 UTC, sastels commented
@siovene fixed that test! Now I've tried to add the camera test, but I think I need to mock things so that looking up the camera works... getting an error
```

  ● SensorService › getPrintableProperty › should work for cameras'

    TypeError: Cannot read properties of undefined (reading 'pipe')

      143 |           this.store$.dispatch(new LoadEquipmentItem(payload));
      144 |
    > 145 |           cameras$.push(this.store$.select(selectEquipmentItem, payload).pipe(
          |                                                                         ^
      146 |             filter(camera => !!camera),
      147 |             take(1),
      148 |             map(

      at SensorService.getPrintableProperty$ (src/app/features/equipment/services/sensor.service.ts:145:73)
      at src/app/features/equipment/services/sensor.service.spec.ts:107:15
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:412:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3833:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:411:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:169:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4333:34)
```

2023-07-08 18:23 UTC, siovene commented
@sastels here's how to fix that test:

```diff
diff --git a/src/app/features/equipment/services/sensor.service.spec.ts b/src/app/features/equipment/services/sensor.service.spec.ts
index 5db26114..4f095e66 100644
--- a/src/app/features/equipment/services/sensor.service.spec.ts
+++ b/src/app/features/equipment/services/sensor.service.spec.ts
@@ -4,19 +4,22 @@ import { AppModule } from "@app/app.module";
 import { SensorDisplayProperty, SensorService } from "@features/equipment/services/sensor.service";
 import { SensorGenerator } from "@features/equipment/generators/sensor.generator";
 import { CameraGenerator } from "@features/equipment/generators/camera.generator";
-import { SensorInterface } from "@features/equipment/types/sensor.interface";
-import { ColorOrMono } from "@features/equipment/types/sensor.interface";
+import { ColorOrMono, SensorInterface } from "@features/equipment/types/sensor.interface";
 import { of } from "rxjs";
+import { MockStore, provideMockStore } from "@ngrx/store/testing";
+import { initialState } from "@app/store/state";
 
 describe("SensorService", () => {
   let service: SensorService;
+  let store: MockStore;
   let sensor: SensorInterface;
   let camera1 = CameraGenerator.camera({ id: 1, name: "Camera 1" });
   let camera2 = CameraGenerator.camera({ id: 2, name: "Camera 2" });
 
   beforeEach(async () => {
-    await MockBuilder(SensorService, AppModule);
+    await MockBuilder(SensorService, AppModule).provide(provideMockStore({ initialState }));
     service = TestBed.inject(SensorService);
+    store = TestBed.inject(MockStore);
     jest.spyOn(service.translateService, "instant").mockImplementation(s => s);
     jest.spyOn(service.translateService, "stream").mockImplementation(s => of(s));
     sensor = SensorGenerator.sensor({
@@ -104,8 +107,11 @@ describe("SensorService", () => {
     });
 
     it("should work for cameras'", done => {
+      const state = { ...initialState };
+      state.equipment.equipmentItems = [camera1, camera2];
+      store.setState(state);
       service.getPrintableProperty$(sensor, SensorDisplayProperty.CAMERAS).subscribe(value => {
-        expect(value).toEqual("Mono");
+        expect(value).toEqual("Test Brand Camera 1, Test Brand Camera 2");
         done();
       });
     });
```

The error was caused by the fact that `this.store$.select(selectEquipmentItem, payload)` in `getPrintableProperty$` was never completing, as we don't have anything in the store. The fix is to provide a mock store, and put the cameras into it.

2023-07-15 00:00 UTC, sastels commented
@siovene yes! I was playing around before trying to do something like `TestBed.inject(CameraService);` here but that didn't work, as you can imagine 😅 

ok, so what else is there to do here... Could see about a cypress test similar to `select-existing-camera.js` maybe, like a `select-existing-sensor.js`? I'm a bit inclined to move on to another notion card instead though, been on this one for a while :) What do you think?

2023-07-15 07:36 UTC, siovene commented
@sastels yeah I agree, this does not need further testing. In general, I reserve cypress tests to things that are more major and have the potential to break by touching something else :)

I'll give it one final look and manual testing, and then merge. Feel free to pick something else from the list and thank you so much for your contribution! ❤️

2023-07-17 11:37 UTC, merged

2023-07-17 12:33 UTC, siovene commented
@sastels we're live! Thank you so much for your contribution!